<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class CompanyResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'companySystemID' => $this->companySystemID,
            'CompanyID' => $this->CompanyID,
            'CompanyName' => $this->CompanyName,
            'CompanyNameLocalized' => $this->CompanyNameLocalized,
            'LocalName' => $this->LocalName,
            'MasterLevel' => $this->MasterLevel,
            'CompanyLevel' => $this->CompanyLevel,
            'masterComapanySystemID' => $this->masterComapanySystemID,
            'masterComapanyID' => $this->masterComapanyID,
            'masterCompanySystemIDReorting' => $this->masterCompanySystemIDReorting,
            'masterComapanyIDReporting' => $this->masterComapanyIDReporting,
            'companyShortCode' => $this->companyShortCode,
            'orgListOrder' => $this->orgListOrder,
            'orgListSordOrder' => $this->orgListSordOrder,
            'sortOrder' => $this->sortOrder,
            'listOrder' => $this->listOrder,
            'CompanyAddress' => $this->CompanyAddress,
            'CompanyAddressSecondaryLanguage' => $this->CompanyAddressSecondaryLanguage,
            'companyCountry' => $this->companyCountry,
            'CompanyTelephone' => $this->CompanyTelephone,
            'CompanyFax' => $this->CompanyFax,
            'CompanyEmail' => $this->CompanyEmail,
            'CompanyURL' => $this->CompanyURL,
            'SubscriptionStarted' => $this->SubscriptionStarted,
            'SubscriptionUpTo' => $this->SubscriptionUpTo,
            'ContactPerson' => $this->ContactPerson,
            'ContactPersonTelephone' => $this->ContactPersonTelephone,
            'ContactPersonFax' => $this->ContactPersonFax,
            'ContactPersonEmail' => $this->ContactPersonEmail,
            'registrationNumber' => $this->registrationNumber,
            'companyLogo' => $this->companyLogo,
            'logoPath' => $this->logoPath,
            'companyGroupLogo' => $this->companyGroupLogo,
            'reportingCurrency' => $this->reportingCurrency,
            'localCurrencyID' => $this->localCurrencyID,
            'mainFormName' => $this->mainFormName,
            'menuInitialImage' => $this->menuInitialImage,
            'menuInitialSelectedImage' => $this->menuInitialSelectedImage,
            'policyItemIssueTollerence' => $this->policyItemIssueTollerence,
            'policyAddonPercentage' => $this->policyAddonPercentage,
            'policyPOAppDayDiff' => $this->policyPOAppDayDiff,
            'policyStockAdjWacCurrentYN' => $this->policyStockAdjWacCurrentYN,
            'policyDepreciationRunDate' => $this->policyDepreciationRunDate,
            'isGroup' => $this->isGroup,
            'isAttachementYN' => $this->isAttachementYN,
            'reportingCriteria' => $this->reportingCriteria,
            'reportingCriteriaFormQuery' => $this->reportingCriteriaFormQuery,
            'supplierReportingCriteria' => $this->supplierReportingCriteria,
            'supplierReportingCriteriaFormQuery' => $this->supplierReportingCriteriaFormQuery,
            'supplierPOSavReportingCriteria' => $this->supplierPOSavReportingCriteria,
            'supplierPOSavReportingCriteriaFormQuery' => $this->supplierPOSavReportingCriteriaFormQuery,
            'supplierPOSpentReportingCriteriaFormQuery' => $this->supplierPOSpentReportingCriteriaFormQuery,
            'exchangeGainLossGLCodeSystemID' => $this->exchangeGainLossGLCodeSystemID,
            'exchangeGainLossGLCode' => $this->exchangeGainLossGLCode,
            'exchangeLossGLCode' => $this->exchangeLossGLCode,
            'exchangeGainGLCode' => $this->exchangeGainGLCode,
            'exchangeProvisionGLCode' => $this->exchangeProvisionGLCode,
            'exchangeProvisionGLCodeAR' => $this->exchangeProvisionGLCodeAR,
            'isApprovalByServiceLine' => $this->isApprovalByServiceLine,
            'isApprovalByServiceLineFinance' => $this->isApprovalByServiceLineFinance,
            'isTaxYN' => $this->isTaxYN,
            'isActive' => $this->isActive,
            'isActiveGroup' => $this->isActiveGroup,
            'showInCombo' => $this->showInCombo,
            'allowBackDatedGRV' => $this->allowBackDatedGRV,
            'allowCustomerInvWithoutContractID' => $this->allowCustomerInvWithoutContractID,
            'checkMaxQty' => $this->checkMaxQty,
            'itemCodeMustInPR' => $this->itemCodeMustInPR,
            'op_OnOpenPopUpYN' => $this->op_OnOpenPopUpYN,
            'showInNewRILRQHSE' => $this->showInNewRILRQHSE,
            'vatRegisteredYN' => $this->vatRegisteredYN,
            'vatRegistratonNumber' => $this->vatRegistratonNumber,
            'vatInputGLCodeSystemID' => $this->vatInputGLCodeSystemID,
            'vatInputGLCode' => $this->vatInputGLCode,
            'vatOutputGLCodeSystemID' => $this->vatOutputGLCodeSystemID,
            'vatOutputGLCode' => $this->vatOutputGLCode,
            'createdUserGroup' => $this->createdUserGroup,
            'createdPcID' => $this->createdPcID,
            'createdUserID' => $this->createdUserID,
            'modifiedPc' => $this->modifiedPc,
            'modifiedUser' => $this->modifiedUser,
            'createdDateTime' => $this->createdDateTime,
            'timeStamp' => $this->timeStamp,
            'isDemo' => $this->isDemo,
            'isHrmsIntergrated' => $this->isHrmsIntergrated,
            'pmsErpIntegrated' => $this->pmsErpIntegrated,
            'jsrsNumber' => $this->jsrsNumber,
            'jsrsExpiryDate' => $this->jsrsExpiryDate,
            'taxCardNo' => $this->taxCardNo,
            'revenuePercentageForInterCompanyInventoryTransfer' => $this->revenuePercentageForInterCompanyInventoryTransfer,
            'revenuePercentageForInterCompanyAssetTransfer' => $this->revenuePercentageForInterCompanyAssetTransfer,
            'qhseApiKey' => $this->qhseApiKey,
            'isAttachmentFromS3' => $this->isAttachmentFromS3,
            'helpDeskApiKey' => $this->helpDeskApiKey,
            'helpDeskUrl' => $this->helpDeskUrl,
            'helpDeskProductId' => $this->helpDeskProductId,
            'helpDeskTenant' => $this->helpDeskTenant,
            'group_two' => $this->group_two,
            'group_type' => $this->group_type,
            'holding_percentage' => $this->holding_percentage,
            'holding_updated_date' => $this->holding_updated_date
        ];
    }
}
