<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class EmployeesDetailsResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'EIdNo' => $this->EIdNo,
            'serialNo' => $this->serialNo,
            'ECode' => $this->ECode,
            'EmpSecondaryCode' => $this->EmpSecondaryCode,
            'EmpTitleId' => $this->EmpTitleId,
            'manPowerNo' => $this->manPowerNo,
            'ssoNo' => $this->ssoNo,
            'EmpDesignationId' => $this->EmpDesignationId,
            'is_top_of_company' => $this->is_top_of_company,
            'Ename1' => $this->Ename1,
            'Ename2' => $this->Ename2,
            'AirportDestinationID' => $this->AirportDestinationID,
            'Ename3' => $this->Ename3,
            'Ename4' => $this->Ename4,
            'empSecondName' => $this->empSecondName,
            'EFamilyName' => $this->EFamilyName,
            'initial' => $this->initial,
            'EmpShortCode' => $this->EmpShortCode,
            'Enameother1' => $this->Enameother1,
            'Enameother2' => $this->Enameother2,
            'Enameother3' => $this->Enameother3,
            'Enameother4' => $this->Enameother4,
            'empSecondNameOther' => $this->empSecondNameOther,
            'EFamilyNameOther' => $this->EFamilyNameOther,
            'empSignature' => $this->empSignature,
            'EmpImage' => $this->EmpImage,
            'EthumbnailImage' => $this->EthumbnailImage,
            'Gender' => $this->Gender,
            'payee_emp_type' => $this->payee_emp_type,
            'EpAddress1' => $this->EpAddress1,
            'EpAddress2' => $this->EpAddress2,
            'EpAddress3' => $this->EpAddress3,
            'EpAddress4' => $this->EpAddress4,
            'ZipCode' => $this->ZipCode,
            'EpTelephone' => $this->EpTelephone,
            'EpFax' => $this->EpFax,
            'EpMobile' => $this->EpMobile,
            'EcAddress1' => $this->EcAddress1,
            'EcAddress2' => $this->EcAddress2,
            'EcAddress3' => $this->EcAddress3,
            'EcAddress4' => $this->EcAddress4,
            'EcPOBox' => $this->EcPOBox,
            'EcPC' => $this->EcPC,
            'EcArea' => $this->EcArea,
            'EcTel' => $this->EcTel,
            'EcExtension' => $this->EcExtension,
            'EcFax' => $this->EcFax,
            'EcMobile' => $this->EcMobile,
            'EEmail' => $this->EEmail,
            'personalEmail' => $this->personalEmail,
            'EDOB' => $this->EDOB,
            'EDOJ' => $this->EDOJ,
            'NIC' => $this->NIC,
            'insuranceNo' => $this->insuranceNo,
            'EPassportNO' => $this->EPassportNO,
            'EPassportExpiryDate' => $this->EPassportExpiryDate,
            'EVisaExpiryDate' => $this->EVisaExpiryDate,
            'Nid' => $this->Nid,
            'Rid' => $this->Rid,
            'AirportDestination' => $this->AirportDestination,
            'travelFrequencyID' => $this->travelFrequencyID,
            'commissionSchemeID' => $this->commissionSchemeID,
            'medicalInfo' => $this->medicalInfo,
            'SchMasterId' => $this->SchMasterId,
            'branchID' => $this->branchID,
            'userType' => $this->userType,
            'isSystemUserYN' => $this->isSystemUserYN,
            'UserName' => $this->UserName,
            'Password' => $this->Password,
            'isDeleted' => $this->isDeleted,
            'HouseID' => $this->HouseID,
            'HouseCatID' => $this->HouseCatID,
            'HPID' => $this->HPID,
            'isPayrollEmployee' => $this->isPayrollEmployee,
            'payCurrencyID' => $this->payCurrencyID,
            'payCurrency' => $this->payCurrency,
            'isLeft' => $this->isLeft,
            'DateLeft' => $this->DateLeft,
            'LeftComment' => $this->LeftComment,
            'BloodGroup' => $this->BloodGroup,
            'DateAssumed' => $this->DateAssumed,
            'probationPeriod' => $this->probationPeriod,
            'isDischarged' => $this->isDischarged,
            'dischargedByEmpID' => $this->dischargedByEmpID,
            'EmployeeConType' => $this->EmployeeConType,
            'dischargedDate' => $this->dischargedDate,
            'lastWorkingDate' => $this->lastWorkingDate,
            'gratuityCalculationDate' => $this->gratuityCalculationDate,
            'dischargeTypeID' => $this->dischargeTypeID,
            'dischargeReasonID' => $this->dischargeReasonID,
            'dischargedComment' => $this->dischargedComment,
            'eligibleToRehire' => $this->eligibleToRehire,
            'finalSettlementDoneYN' => $this->finalSettlementDoneYN,
            'MaritialStatus' => $this->MaritialStatus,
            'Nationality' => $this->Nationality,
            'isLoginAttempt' => $this->isLoginAttempt,
            'isChangePassword' => $this->isChangePassword,
            'created_by' => $this->created_by,
            'CreatedUserName' => $this->CreatedUserName,
            'CreatedDate' => $this->CreatedDate,
            'CreatedPC' => $this->CreatedPC,
            'modified_by' => $this->modified_by,
            'modified_at' => $this->modified_at,
            'ModifiedUserName' => $this->ModifiedUserName,
            'Timestamp' => $this->Timestamp,
            'ModifiedPC' => $this->ModifiedPC,
            'isActive' => $this->isActive,
            'NoOfLoginAttempt' => $this->NoOfLoginAttempt,
            'languageID' => $this->languageID,
            'locationID' => $this->locationID,
            'sponsorID' => $this->sponsorID,
            'mobileCreditLimit' => $this->mobileCreditLimit,
            'segmentID' => $this->segmentID,
            'Erp_companyID' => $this->Erp_companyID,
            'secondary_company_id' => $this->secondary_company_id,
            'insurance_category' => $this->insurance_category,
            'insurance_code' => $this->insurance_code,
            'cover_from' => $this->cover_from,
            'cover_to' => $this->cover_to,
            'floorID' => $this->floorID,
            'deviceID' => $this->deviceID,
            'empMachineID' => $this->empMachineID,
            'leaveGroupID' => $this->leaveGroupID,
            'isMobileCheckIn' => $this->isMobileCheckIn,
            'isCheckin' => $this->isCheckin,
            'token' => $this->token,
            'overTimeGroup' => $this->overTimeGroup,
            'familyStatusID' => $this->familyStatusID,
            'gratuityID' => $this->gratuityID,
            'isSystemAdmin' => $this->isSystemAdmin,
            'isHRAdmin' => $this->isHRAdmin,
            'contractStartDate' => $this->contractStartDate,
            'contractEndDate' => $this->contractEndDate,
            'contractRefNo' => $this->contractRefNo,
            'confirmed_by' => $this->confirmed_by,
            'empConfirmDate' => $this->empConfirmDate,
            'empConfirmedYN' => $this->empConfirmedYN,
            'rejoinDate' => $this->rejoinDate,
            'previousEmpID' => $this->previousEmpID,
            'gradeID' => $this->gradeID,
            'pos_userGroupMasterID' => $this->pos_userGroupMasterID,
            'pos_userGroupMasterID_gpos' => $this->pos_userGroupMasterID_gpos,
            'pos_barCode' => $this->pos_barCode,
            'isLocalPosSyncEnable' => $this->isLocalPosSyncEnable,
            'isLocalPosSalesRptEnable' => $this->isLocalPosSalesRptEnable,
            'tibianType' => $this->tibianType,
            'LocalPOSUserType' => $this->LocalPOSUserType,
            'last_login' => $this->last_login,
            'exclude_PASI' => $this->exclude_PASI
        ];
    }
}
