<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PaySpplierInvoiceMasterResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'PayMasterAutoId' => $this->PayMasterAutoId,
            'companySystemID' => $this->companySystemID,
            'companyID' => $this->companyID,
            'documentSystemID' => $this->documentSystemID,
            'documentID' => $this->documentID,
            'projectID' => $this->projectID,
            'serialNo' => $this->serialNo,
            'companyFinanceYearID' => $this->companyFinanceYearID,
            'FYBiggin' => $this->FYBiggin,
            'FYEnd' => $this->FYEnd,
            'companyFinancePeriodID' => $this->companyFinancePeriodID,
            'FYPeriodDateFrom' => $this->FYPeriodDateFrom,
            'FYPeriodDateTo' => $this->FYPeriodDateTo,
            'BPVcode' => $this->BPVcode,
            'BPVdate' => $this->BPVdate,
            'BPVbank' => $this->BPVbank,
            'BPVAccount' => $this->BPVAccount,
            'BPVchequeNo' => $this->BPVchequeNo,
            'BPVchequeDate' => $this->BPVchequeDate,
            'BPVNarration' => $this->BPVNarration,
            'BPVbankCurrency' => $this->BPVbankCurrency,
            'BPVbankCurrencyER' => $this->BPVbankCurrencyER,
            'directPaymentpayeeYN' => $this->directPaymentpayeeYN,
            'directPaymentPayeeSelectEmp' => $this->directPaymentPayeeSelectEmp,
            'directPaymentPayeeEmpID' => $this->directPaymentPayeeEmpID,
            'directPaymentPayee' => $this->directPaymentPayee,
            'directPayeeCurrency' => $this->directPayeeCurrency,
            'directPayeeBankMemo' => $this->directPayeeBankMemo,
            'BPVsupplierID' => $this->BPVsupplierID,
            'supplierGLCodeSystemID' => $this->supplierGLCodeSystemID,
            'supplierGLCode' => $this->supplierGLCode,
            'supplierTransCurrencyID' => $this->supplierTransCurrencyID,
            'supplierTransCurrencyER' => $this->supplierTransCurrencyER,
            'supplierDefCurrencyID' => $this->supplierDefCurrencyID,
            'supplierDefCurrencyER' => $this->supplierDefCurrencyER,
            'localCurrencyID' => $this->localCurrencyID,
            'localCurrencyER' => $this->localCurrencyER,
            'companyRptCurrencyID' => $this->companyRptCurrencyID,
            'companyRptCurrencyER' => $this->companyRptCurrencyER,
            'payAmountBank' => $this->payAmountBank,
            'payAmountSuppTrans' => $this->payAmountSuppTrans,
            'payAmountSuppDef' => $this->payAmountSuppDef,
            'payAmountCompLocal' => $this->payAmountCompLocal,
            'payAmountCompRpt' => $this->payAmountCompRpt,
            'suppAmountDocTotal' => $this->suppAmountDocTotal,
            'createMonthlyDeduction' => $this->createMonthlyDeduction,
            'confirmedYN' => $this->confirmedYN,
            'confirmedByEmpSystemID' => $this->confirmedByEmpSystemID,
            'confirmedByEmpID' => $this->confirmedByEmpID,
            'confirmedByName' => $this->confirmedByName,
            'confirmedDate' => $this->confirmedDate,
            'approved' => $this->approved,
            'approvedDate' => $this->approvedDate,
            'approvedByUserID' => $this->approvedByUserID,
            'approvedByUserSystemID' => $this->approvedByUserSystemID,
            'postedDate' => $this->postedDate,
            'invoiceType' => $this->invoiceType,
            'matchInvoice' => $this->matchInvoice,
            'trsCollectedYN' => $this->trsCollectedYN,
            'trsCollectedByEmpSystemID' => $this->trsCollectedByEmpSystemID,
            'trsCollectedByEmpID' => $this->trsCollectedByEmpID,
            'trsCollectedByEmpName' => $this->trsCollectedByEmpName,
            'trsCollectedDate' => $this->trsCollectedDate,
            'trsClearedYN' => $this->trsClearedYN,
            'trsClearedDate' => $this->trsClearedDate,
            'trsClearedByEmpSystemID' => $this->trsClearedByEmpSystemID,
            'trsClearedByEmpID' => $this->trsClearedByEmpID,
            'trsClearedByEmpName' => $this->trsClearedByEmpName,
            'trsClearedAmount' => $this->trsClearedAmount,
            'bankClearedYN' => $this->bankClearedYN,
            'bankClearedAmount' => $this->bankClearedAmount,
            'bankReconciliationDate' => $this->bankReconciliationDate,
            'bankClearedDate' => $this->bankClearedDate,
            'bankClearedByEmpSystemID' => $this->bankClearedByEmpSystemID,
            'bankClearedByEmpID' => $this->bankClearedByEmpID,
            'bankClearedByEmpName' => $this->bankClearedByEmpName,
            'chequePaymentYN' => $this->chequePaymentYN,
            'chequePrintedYN' => $this->chequePrintedYN,
            'chequePrintedDateTime' => $this->chequePrintedDateTime,
            'chequePrintedByEmpSystemID' => $this->chequePrintedByEmpSystemID,
            'chequePrintedByEmpID' => $this->chequePrintedByEmpID,
            'chequePrintedByEmpName' => $this->chequePrintedByEmpName,
            'chequeSentToTreasury' => $this->chequeSentToTreasury,
            'chequeSentToTreasuryByEmpSystemID' => $this->chequeSentToTreasuryByEmpSystemID,
            'chequeSentToTreasuryByEmpID' => $this->chequeSentToTreasuryByEmpID,
            'chequeSentToTreasuryByEmpName' => $this->chequeSentToTreasuryByEmpName,
            'chequeSentToTreasuryDate' => $this->chequeSentToTreasuryDate,
            'chequeReceivedByTreasury' => $this->chequeReceivedByTreasury,
            'chequeReceivedByTreasuryByEmpSystemID' => $this->chequeReceivedByTreasuryByEmpSystemID,
            'chequeReceivedByTreasuryByEmpID' => $this->chequeReceivedByTreasuryByEmpID,
            'chequeReceivedByTreasuryByEmpName' => $this->chequeReceivedByTreasuryByEmpName,
            'chequeReceivedByTreasuryDate' => $this->chequeReceivedByTreasuryDate,
            'timesReferred' => $this->timesReferred,
            'matchingConfirmedYN' => $this->matchingConfirmedYN,
            'matchingConfirmedByEmpSystemID' => $this->matchingConfirmedByEmpSystemID,
            'matchingConfirmedByEmpID' => $this->matchingConfirmedByEmpID,
            'matchingConfirmedByName' => $this->matchingConfirmedByName,
            'matchingConfirmedDate' => $this->matchingConfirmedDate,
            'refferedBackYN' => $this->refferedBackYN,
            'RollLevForApp_curr' => $this->RollLevForApp_curr,
            'noOfApprovalLevels' => $this->noOfApprovalLevels,
            'isRelatedPartyYN' => $this->isRelatedPartyYN,
            'advancePaymentTypeID' => $this->advancePaymentTypeID,
            'isPdcChequeYN' => $this->isPdcChequeYN,
            'finalSettlementYN' => $this->finalSettlementYN,
            'partyTblID' => $this->partyTblID,
            'expenseClaimOrPettyCash' => $this->expenseClaimOrPettyCash,
            'interCompanyToSystemID' => $this->interCompanyToSystemID,
            'interCompanyToID' => $this->interCompanyToID,
            'ReversedYN' => $this->ReversedYN,
            'cancelYN' => $this->cancelYN,
            'cancelComment' => $this->cancelComment,
            'cancelDate' => $this->cancelDate,
            'cancelledByEmpSystemID' => $this->cancelledByEmpSystemID,
            'canceledByEmpID' => $this->canceledByEmpID,
            'canceledByEmpName' => $this->canceledByEmpName,
            'createdUserGroup' => $this->createdUserGroup,
            'createdUserSystemID' => $this->createdUserSystemID,
            'createdUserID' => $this->createdUserID,
            'createdPcID' => $this->createdPcID,
            'modifiedUserSystemID' => $this->modifiedUserSystemID,
            'modifiedUser' => $this->modifiedUser,
            'modifiedPc' => $this->modifiedPc,
            'createdDateTime' => $this->createdDateTime,
            'timestamp' => $this->timestamp,
            'rcmActivated' => $this->rcmActivated,
            'retentionVatAmount' => $this->retentionVatAmount,
            'VATAmount' => $this->VATAmount,
            'VATAmountLocal' => $this->VATAmountLocal,
            'VATAmountRpt' => $this->VATAmountRpt,
            'netAmount' => $this->netAmount,
            'netAmountLocal' => $this->netAmountLocal,
            'netAmountRpt' => $this->netAmountRpt,
            'VATPercentage' => $this->VATPercentage,
            'pdcChequeYN' => $this->pdcChequeYN,
            'bankAccountBalance' => $this->bankAccountBalance,
            'payment_mode' => $this->payment_mode,
            'advanceAccountSystemID' => $this->advanceAccountSystemID,
            'AdvanceAccount' => $this->AdvanceAccount,
            'VATAmountBank' => $this->VATAmountBank,
            'applyVAT' => $this->applyVAT
        ];
    }
}
