<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PurchaseOrderDetailResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'purchaseOrderDetailsID' => $this->purchaseOrderDetailsID,
            'purchaseOrderMasterID' => $this->purchaseOrderMasterID,
            'purchaseProcessDetailID' => $this->purchaseProcessDetailID,
            'POProcessMasterID' => $this->POProcessMasterID,
            'WO_purchaseOrderMasterID' => $this->WO_purchaseOrderMasterID,
            'WP_purchaseOrderDetailsID' => $this->WP_purchaseOrderDetailsID,
            'purchaseRequestDetailsID' => $this->purchaseRequestDetailsID,
            'purchaseRequestID' => $this->purchaseRequestID,
            'companySystemID' => $this->companySystemID,
            'companyID' => $this->companyID,
            'departmentID' => $this->departmentID,
            'serviceLineSystemID' => $this->serviceLineSystemID,
            'serviceLineCode' => $this->serviceLineCode,
            'madeLocallyYN' => $this->madeLocallyYN,
            'itemCode' => $this->itemCode,
            'itemPrimaryCode' => $this->itemPrimaryCode,
            'itemDescription' => $this->itemDescription,
            'itemFinanceCategoryID' => $this->itemFinanceCategoryID,
            'itemFinanceCategorySubID' => $this->itemFinanceCategorySubID,
            'financeGLcodebBSSystemID' => $this->financeGLcodebBSSystemID,
            'financeGLcodebBS' => $this->financeGLcodebBS,
            'financeGLcodePLSystemID' => $this->financeGLcodePLSystemID,
            'financeGLcodePL' => $this->financeGLcodePL,
            'includePLForGRVYN' => $this->includePLForGRVYN,
            'supplierPartNumber' => $this->supplierPartNumber,
            'unitOfMeasure' => $this->unitOfMeasure,
            'altUnit' => $this->altUnit,
            'altUnitValue' => $this->altUnitValue,
            'itemClientReferenceNumberMasterID' => $this->itemClientReferenceNumberMasterID,
            'clientReferenceNumber' => $this->clientReferenceNumber,
            'requestedQty' => $this->requestedQty,
            'noQty' => $this->noQty,
            'balanceQty' => $this->balanceQty,
            'noOfDays' => $this->noOfDays,
            'unitCost' => $this->unitCost,
            'discountPercentage' => $this->discountPercentage,
            'discountAmount' => $this->discountAmount,
            'netAmount' => $this->netAmount,
            'markupPercentage' => $this->markupPercentage,
            'markupTransactionAmount' => $this->markupTransactionAmount,
            'markupLocalAmount' => $this->markupLocalAmount,
            'markupReportingAmount' => $this->markupReportingAmount,
            'budgetYear' => $this->budgetYear,
            'prBelongsYear' => $this->prBelongsYear,
            'isAccrued' => $this->isAccrued,
            'budjetAmtLocal' => $this->budjetAmtLocal,
            'budjetAmtRpt' => $this->budjetAmtRpt,
            'comment' => $this->comment,
            'supplierDefaultCurrencyID' => $this->supplierDefaultCurrencyID,
            'supplierDefaultER' => $this->supplierDefaultER,
            'supplierItemCurrencyID' => $this->supplierItemCurrencyID,
            'foreignToLocalER' => $this->foreignToLocalER,
            'companyReportingCurrencyID' => $this->companyReportingCurrencyID,
            'companyReportingER' => $this->companyReportingER,
            'localCurrencyID' => $this->localCurrencyID,
            'localCurrencyER' => $this->localCurrencyER,
            'addonDistCost' => $this->addonDistCost,
            'GRVcostPerUnitLocalCur' => $this->GRVcostPerUnitLocalCur,
            'GRVcostPerUnitSupDefaultCur' => $this->GRVcostPerUnitSupDefaultCur,
            'GRVcostPerUnitSupTransCur' => $this->GRVcostPerUnitSupTransCur,
            'GRVcostPerUnitComRptCur' => $this->GRVcostPerUnitComRptCur,
            'addonPurchaseReturnCost' => $this->addonPurchaseReturnCost,
            'purchaseRetcostPerUnitLocalCur' => $this->purchaseRetcostPerUnitLocalCur,
            'purchaseRetcostPerUniSupDefaultCur' => $this->purchaseRetcostPerUniSupDefaultCur,
            'purchaseRetcostPerUnitTranCur' => $this->purchaseRetcostPerUnitTranCur,
            'purchaseRetcostPerUnitRptCur' => $this->purchaseRetcostPerUnitRptCur,
            'receivedQty' => $this->receivedQty,
            'GRVSelectedYN' => $this->GRVSelectedYN,
            'goodsRecievedYN' => $this->goodsRecievedYN,
            'logisticSelectedYN' => $this->logisticSelectedYN,
            'logisticRecievedYN' => $this->logisticRecievedYN,
            'isAccruedYN' => $this->isAccruedYN,
            'accrualJVID' => $this->accrualJVID,
            'timesReferred' => $this->timesReferred,
            'totalWHTAmount' => $this->totalWHTAmount,
            'WHTBearedBySupplier' => $this->WHTBearedBySupplier,
            'WHTBearedByCompany' => $this->WHTBearedByCompany,
            'VATPercentage' => $this->VATPercentage,
            'VATAmount' => $this->VATAmount,
            'VATAmountLocal' => $this->VATAmountLocal,
            'VATAmountRpt' => $this->VATAmountRpt,
            'VATApplicableOn' => $this->VATApplicableOn,
            'manuallyClosed' => $this->manuallyClosed,
            'manuallyClosedByEmpSystemID' => $this->manuallyClosedByEmpSystemID,
            'manuallyClosedByEmpID' => $this->manuallyClosedByEmpID,
            'manuallyClosedByEmpName' => $this->manuallyClosedByEmpName,
            'manuallyClosedDate' => $this->manuallyClosedDate,
            'manuallyClosedComment' => $this->manuallyClosedComment,
            'createdUserGroup' => $this->createdUserGroup,
            'createdPcID' => $this->createdPcID,
            'createdUserID' => $this->createdUserID,
            'modifiedPc' => $this->modifiedPc,
            'modifiedUser' => $this->modifiedUser,
            'createdDateTime' => $this->createdDateTime,
            'supplierCatalogDetailID' => $this->supplierCatalogDetailID,
            'supplierCatalogMasterID' => $this->supplierCatalogMasterID,
            'timeStamp' => $this->timeStamp,
            'detail_project_id' => $this->detail_project_id,
            'vatMasterCategoryID' => $this->vatMasterCategoryID,
            'vatSubCategoryID' => $this->vatSubCategoryID,
            'exempt_vat_portion' => $this->exempt_vat_portion,
            'contractID' => $this->contractID,
            'contractDescription' => $this->contractDescription
        ];
    }
}
