<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PurchaseOrderMasterResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'purchaseOrderID' => $this->purchaseOrderID,
            'poProcessId' => $this->poProcessId,
            'companySystemID' => $this->companySystemID,
            'companyID' => $this->companyID,
            'departmentID' => $this->departmentID,
            'orderType' => $this->orderType,
            'amended' => $this->amended,
            'projectID' => $this->projectID,
            'serviceLineSystemID' => $this->serviceLineSystemID,
            'serviceLine' => $this->serviceLine,
            'companyAddress' => $this->companyAddress,
            'documentSystemID' => $this->documentSystemID,
            'documentID' => $this->documentID,
            'purchaseOrderCode' => $this->purchaseOrderCode,
            'serialNumber' => $this->serialNumber,
            'supplierID' => $this->supplierID,
            'supplierPrimaryCode' => $this->supplierPrimaryCode,
            'supplierName' => $this->supplierName,
            'supplierAddress' => $this->supplierAddress,
            'supplierTelephone' => $this->supplierTelephone,
            'supplierFax' => $this->supplierFax,
            'supplierEmail' => $this->supplierEmail,
            'creditPeriod' => $this->creditPeriod,
            'expectedDeliveryDate' => $this->expectedDeliveryDate,
            'narration' => $this->narration,
            'poLocation' => $this->poLocation,
            'financeCategory' => $this->financeCategory,
            'referenceNumber' => $this->referenceNumber,
            'shippingAddressID' => $this->shippingAddressID,
            'shippingAddressDescriprion' => $this->shippingAddressDescriprion,
            'invoiceToAddressID' => $this->invoiceToAddressID,
            'invoiceToAddressDescription' => $this->invoiceToAddressDescription,
            'soldToAddressID' => $this->soldToAddressID,
            'soldToAddressDescriprion' => $this->soldToAddressDescriprion,
            'paymentTerms' => $this->paymentTerms,
            'deliveryTerms' => $this->deliveryTerms,
            'panaltyTerms' => $this->panaltyTerms,
            'localCurrencyID' => $this->localCurrencyID,
            'localCurrencyER' => $this->localCurrencyER,
            'companyReportingCurrencyID' => $this->companyReportingCurrencyID,
            'companyReportingER' => $this->companyReportingER,
            'supplierDefaultCurrencyID' => $this->supplierDefaultCurrencyID,
            'supplierDefaultER' => $this->supplierDefaultER,
            'supplierTransactionCurrencyID' => $this->supplierTransactionCurrencyID,
            'supplierTransactionER' => $this->supplierTransactionER,
            'poConfirmedYN' => $this->poConfirmedYN,
            'poConfirmedByEmpSystemID' => $this->poConfirmedByEmpSystemID,
            'poConfirmedByEmpID' => $this->poConfirmedByEmpID,
            'poConfirmedByName' => $this->poConfirmedByName,
            'poConfirmedDate' => $this->poConfirmedDate,
            'poCancelledYN' => $this->poCancelledYN,
            'poCancelledBySystemID' => $this->poCancelledBySystemID,
            'poCancelledBy' => $this->poCancelledBy,
            'poCancelledByName' => $this->poCancelledByName,
            'poCancelledDate' => $this->poCancelledDate,
            'cancelledComments' => $this->cancelledComments,
            'poTotalComRptCurrency' => $this->poTotalComRptCurrency,
            'poTotalLocalCurrency' => $this->poTotalLocalCurrency,
            'poTotalSupplierDefaultCurrency' => $this->poTotalSupplierDefaultCurrency,
            'poTotalSupplierTransactionCurrency' => $this->poTotalSupplierTransactionCurrency,
            'poDiscountPercentage' => $this->poDiscountPercentage,
            'poDiscountAmount' => $this->poDiscountAmount,
            'supplierVATEligible' => $this->supplierVATEligible,
            'VATPercentage' => $this->VATPercentage,
            'VATAmount' => $this->VATAmount,
            'VATAmountLocal' => $this->VATAmountLocal,
            'VATAmountRpt' => $this->VATAmountRpt,
            'shipTocontactPersonID' => $this->shipTocontactPersonID,
            'shipTocontactPersonTelephone' => $this->shipTocontactPersonTelephone,
            'shipTocontactPersonFaxNo' => $this->shipTocontactPersonFaxNo,
            'shipTocontactPersonEmail' => $this->shipTocontactPersonEmail,
            'invoiceTocontactPersonID' => $this->invoiceTocontactPersonID,
            'invoiceTocontactPersonTelephone' => $this->invoiceTocontactPersonTelephone,
            'invoiceTocontactPersonFaxNo' => $this->invoiceTocontactPersonFaxNo,
            'invoiceTocontactPersonEmail' => $this->invoiceTocontactPersonEmail,
            'soldTocontactPersonID' => $this->soldTocontactPersonID,
            'soldTocontactPersonTelephone' => $this->soldTocontactPersonTelephone,
            'soldTocontactPersonFaxNo' => $this->soldTocontactPersonFaxNo,
            'soldTocontactPersonEmail' => $this->soldTocontactPersonEmail,
            'priority' => $this->priority,
            'approved' => $this->approved,
            'approvedDate' => $this->approvedDate,
            'approvedByUserID' => $this->approvedByUserID,
            'approvedByUserSystemID' => $this->approvedByUserSystemID,
            'approval_remarks' => $this->approval_remarks,
            'addOnPercent' => $this->addOnPercent,
            'addOnDefaultPercent' => $this->addOnDefaultPercent,
            'GRVTrackingID' => $this->GRVTrackingID,
            'logisticDoneYN' => $this->logisticDoneYN,
            'poClosedYN' => $this->poClosedYN,
            'grvRecieved' => $this->grvRecieved,
            'invoicedBooked' => $this->invoicedBooked,
            'refferedBackYN' => $this->refferedBackYN,
            'timesReferred' => $this->timesReferred,
            'poType' => $this->poType,
            'poType_N' => $this->poType_N,
            'docRefNo' => $this->docRefNo,
            'RollLevForApp_curr' => $this->RollLevForApp_curr,
            'sentToSupplier' => $this->sentToSupplier,
            'sentToSupplierByEmpSystemID' => $this->sentToSupplierByEmpSystemID,
            'sentToSupplierByEmpID' => $this->sentToSupplierByEmpID,
            'sentToSupplierByEmpName' => $this->sentToSupplierByEmpName,
            'sentToSupplierDate' => $this->sentToSupplierDate,
            'budgetBlockYN' => $this->budgetBlockYN,
            'budgetYear' => $this->budgetYear,
            'hidePOYN' => $this->hidePOYN,
            'hideByEmpSystemID' => $this->hideByEmpSystemID,
            'hideByEmpID' => $this->hideByEmpID,
            'hideByEmpName' => $this->hideByEmpName,
            'hideDate' => $this->hideDate,
            'hideComments' => $this->hideComments,
            'WO_purchaseOrderID' => $this->WO_purchaseOrderID,
            'WO_PeriodFrom' => $this->WO_PeriodFrom,
            'WO_PeriodTo' => $this->WO_PeriodTo,
            'WO_NoOfAutoGenerationTimes' => $this->WO_NoOfAutoGenerationTimes,
            'WO_NoOfGeneratedTimes' => $this->WO_NoOfGeneratedTimes,
            'WO_fullyGenerated' => $this->WO_fullyGenerated,
            'WO_amendYN' => $this->WO_amendYN,
            'WO_amendRequestedDate' => $this->WO_amendRequestedDate,
            'WO_amendRequestedByEmpSystemID' => $this->WO_amendRequestedByEmpSystemID,
            'WO_amendRequestedByEmpID' => $this->WO_amendRequestedByEmpID,
            'WO_confirmedYN' => $this->WO_confirmedYN,
            'WO_confirmedDate' => $this->WO_confirmedDate,
            'WO_confirmedByEmpID' => $this->WO_confirmedByEmpID,
            'WO_terminateYN' => $this->WO_terminateYN,
            'WO_terminatedDate' => $this->WO_terminatedDate,
            'WO_terminatedByEmpID' => $this->WO_terminatedByEmpID,
            'WO_terminateComments' => $this->WO_terminateComments,
            'partiallyGRVAllowed' => $this->partiallyGRVAllowed,
            'logisticsAvailable' => $this->logisticsAvailable,
            'vatRegisteredYN' => $this->vatRegisteredYN,
            'manuallyClosed' => $this->manuallyClosed,
            'manuallyClosedByEmpSystemID' => $this->manuallyClosedByEmpSystemID,
            'manuallyClosedByEmpID' => $this->manuallyClosedByEmpID,
            'manuallyClosedByEmpName' => $this->manuallyClosedByEmpName,
            'manuallyClosedDate' => $this->manuallyClosedDate,
            'manuallyClosedComment' => $this->manuallyClosedComment,
            'supCategoryICVMasterID' => $this->supCategoryICVMasterID,
            'supCategorySubICVID' => $this->supCategorySubICVID,
            'createdUserGroup' => $this->createdUserGroup,
            'createdPcID' => $this->createdPcID,
            'createdUserSystemID' => $this->createdUserSystemID,
            'createdUserID' => $this->createdUserID,
            'modifiedPc' => $this->modifiedPc,
            'modifiedUserSystemID' => $this->modifiedUserSystemID,
            'modifiedUser' => $this->modifiedUser,
            'createdDateTime' => $this->createdDateTime,
            'isSelected' => $this->isSelected,
            'timeStamp' => $this->timeStamp,
            'allocateItemToSegment' => $this->allocateItemToSegment,
            'workOrderGenerateID' => $this->workOrderGenerateID,
            'rcmActivated' => $this->rcmActivated,
            'poTypeID' => $this->poTypeID,
            'categoryID' => $this->categoryID,
            'upload_job_status' => $this->upload_job_status,
            'isBulkItemJobRun' => $this->isBulkItemJobRun,
            'vat_number' => $this->vat_number
        ];
    }
}
