<?php

namespace Database\Factories;

use App\Models\EmployeesDetails;
use Illuminate\Database\Eloquent\Factories\Factory;

class EmployeesDetailsFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = EmployeesDetails::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'serialNo' => $this->faker->randomDigitNotNull,
        'ECode' => $this->faker->word,
        'EmpSecondaryCode' => $this->faker->word,
        'EmpTitleId' => $this->faker->randomDigitNotNull,
        'manPowerNo' => $this->faker->word,
        'ssoNo' => $this->faker->word,
        'EmpDesignationId' => $this->faker->word,
        'is_top_of_company' => $this->faker->word,
        'Ename1' => $this->faker->word,
        'Ename2' => $this->faker->word,
        'AirportDestinationID' => $this->faker->randomDigitNotNull,
        'Ename3' => $this->faker->word,
        'Ename4' => $this->faker->word,
        'empSecondName' => $this->faker->word,
        'EFamilyName' => $this->faker->word,
        'initial' => $this->faker->word,
        'EmpShortCode' => $this->faker->word,
        'Enameother1' => $this->faker->word,
        'Enameother2' => $this->faker->word,
        'Enameother3' => $this->faker->word,
        'Enameother4' => $this->faker->word,
        'empSecondNameOther' => $this->faker->word,
        'EFamilyNameOther' => $this->faker->word,
        'empSignature' => $this->faker->word,
        'EmpImage' => $this->faker->word,
        'EthumbnailImage' => $this->faker->word,
        'Gender' => $this->faker->word,
        'payee_emp_type' => $this->faker->randomDigitNotNull,
        'EpAddress1' => $this->faker->word,
        'EpAddress2' => $this->faker->word,
        'EpAddress3' => $this->faker->word,
        'EpAddress4' => $this->faker->word,
        'ZipCode' => $this->faker->word,
        'EpTelephone' => $this->faker->word,
        'EpFax' => $this->faker->word,
        'EpMobile' => $this->faker->word,
        'EcAddress1' => $this->faker->word,
        'EcAddress2' => $this->faker->word,
        'EcAddress3' => $this->faker->word,
        'EcAddress4' => $this->faker->word,
        'EcPOBox' => $this->faker->word,
        'EcPC' => $this->faker->word,
        'EcArea' => $this->faker->word,
        'EcTel' => $this->faker->word,
        'EcExtension' => $this->faker->word,
        'EcFax' => $this->faker->word,
        'EcMobile' => $this->faker->word,
        'EEmail' => $this->faker->word,
        'personalEmail' => $this->faker->word,
        'EDOB' => $this->faker->word,
        'EDOJ' => $this->faker->word,
        'NIC' => $this->faker->word,
        'insuranceNo' => $this->faker->word,
        'EPassportNO' => $this->faker->word,
        'EPassportExpiryDate' => $this->faker->word,
        'EVisaExpiryDate' => $this->faker->word,
        'Nid' => $this->faker->randomDigitNotNull,
        'Rid' => $this->faker->randomDigitNotNull,
        'AirportDestination' => $this->faker->word,
        'travelFrequencyID' => $this->faker->randomDigitNotNull,
        'commissionSchemeID' => $this->faker->randomDigitNotNull,
        'medicalInfo' => $this->faker->text,
        'SchMasterId' => $this->faker->randomDigitNotNull,
        'branchID' => $this->faker->randomDigitNotNull,
        'userType' => $this->faker->randomDigitNotNull,
        'isSystemUserYN' => $this->faker->randomDigitNotNull,
        'UserName' => $this->faker->word,
        'Password' => $this->faker->word,
        'isDeleted' => $this->faker->randomDigitNotNull,
        'HouseID' => $this->faker->randomDigitNotNull,
        'HouseCatID' => $this->faker->randomDigitNotNull,
        'HPID' => $this->faker->randomDigitNotNull,
        'isPayrollEmployee' => $this->faker->randomDigitNotNull,
        'payCurrencyID' => $this->faker->randomDigitNotNull,
        'payCurrency' => $this->faker->word,
        'isLeft' => $this->faker->randomDigitNotNull,
        'DateLeft' => $this->faker->word,
        'LeftComment' => $this->faker->word,
        'BloodGroup' => $this->faker->randomDigitNotNull,
        'DateAssumed' => $this->faker->word,
        'probationPeriod' => $this->faker->word,
        'isDischarged' => $this->faker->randomDigitNotNull,
        'dischargedByEmpID' => $this->faker->randomDigitNotNull,
        'EmployeeConType' => $this->faker->randomDigitNotNull,
        'dischargedDate' => $this->faker->word,
        'lastWorkingDate' => $this->faker->word,
        'gratuityCalculationDate' => $this->faker->word,
        'dischargeTypeID' => $this->faker->randomDigitNotNull,
        'dischargeReasonID' => $this->faker->randomDigitNotNull,
        'dischargedComment' => $this->faker->word,
        'eligibleToRehire' => $this->faker->word,
        'finalSettlementDoneYN' => $this->faker->randomDigitNotNull,
        'MaritialStatus' => $this->faker->randomDigitNotNull,
        'Nationality' => $this->faker->randomDigitNotNull,
        'isLoginAttempt' => $this->faker->randomDigitNotNull,
        'isChangePassword' => $this->faker->randomDigitNotNull,
        'created_by' => $this->faker->randomDigitNotNull,
        'CreatedUserName' => $this->faker->word,
        'CreatedDate' => $this->faker->date('Y-m-d H:i:s'),
        'CreatedPC' => $this->faker->word,
        'modified_by' => $this->faker->randomDigitNotNull,
        'modified_at' => $this->faker->date('Y-m-d H:i:s'),
        'ModifiedUserName' => $this->faker->word,
        'Timestamp' => $this->faker->date('Y-m-d H:i:s'),
        'ModifiedPC' => $this->faker->word,
        'isActive' => $this->faker->randomDigitNotNull,
        'NoOfLoginAttempt' => $this->faker->randomDigitNotNull,
        'languageID' => $this->faker->randomDigitNotNull,
        'locationID' => $this->faker->randomDigitNotNull,
        'sponsorID' => $this->faker->randomDigitNotNull,
        'mobileCreditLimit' => $this->faker->randomDigitNotNull,
        'segmentID' => $this->faker->randomDigitNotNull,
        'Erp_companyID' => $this->faker->randomDigitNotNull,
        'secondary_company_id' => $this->faker->randomDigitNotNull,
        'insurance_category' => $this->faker->randomDigitNotNull,
        'insurance_code' => $this->faker->text,
        'cover_from' => $this->faker->date('Y-m-d H:i:s'),
        'cover_to' => $this->faker->date('Y-m-d H:i:s'),
        'floorID' => $this->faker->randomDigitNotNull,
        'deviceID' => $this->faker->randomDigitNotNull,
        'empMachineID' => $this->faker->randomDigitNotNull,
        'leaveGroupID' => $this->faker->randomDigitNotNull,
        'isMobileCheckIn' => $this->faker->randomDigitNotNull,
        'isCheckin' => $this->faker->randomDigitNotNull,
        'token' => $this->faker->word,
        'overTimeGroup' => $this->faker->randomDigitNotNull,
        'familyStatusID' => $this->faker->randomDigitNotNull,
        'gratuityID' => $this->faker->randomDigitNotNull,
        'isSystemAdmin' => $this->faker->randomDigitNotNull,
        'isHRAdmin' => $this->faker->randomDigitNotNull,
        'contractStartDate' => $this->faker->word,
        'contractEndDate' => $this->faker->word,
        'contractRefNo' => $this->faker->word,
        'confirmed_by' => $this->faker->randomDigitNotNull,
        'empConfirmDate' => $this->faker->word,
        'empConfirmedYN' => $this->faker->word,
        'rejoinDate' => $this->faker->word,
        'previousEmpID' => $this->faker->randomDigitNotNull,
        'gradeID' => $this->faker->randomDigitNotNull,
        'pos_userGroupMasterID' => $this->faker->word,
        'pos_userGroupMasterID_gpos' => $this->faker->word,
        'pos_barCode' => $this->faker->word,
        'isLocalPosSyncEnable' => $this->faker->randomDigitNotNull,
        'isLocalPosSalesRptEnable' => $this->faker->randomDigitNotNull,
        'tibianType' => $this->faker->randomDigitNotNull,
        'LocalPOSUserType' => $this->faker->word,
        'last_login' => $this->faker->date('Y-m-d H:i:s'),
        'exclude_PASI' => $this->faker->word
        ];
    }
}
