<?php

namespace Database\Factories;

use App\Models\PaySpplierInvoiceMaster;
use Illuminate\Database\Eloquent\Factories\Factory;

class PaySpplierInvoiceMasterFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = PaySpplierInvoiceMaster::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'companySystemID' => $this->faker->randomDigitNotNull,
        'companyID' => $this->faker->word,
        'documentSystemID' => $this->faker->randomDigitNotNull,
        'documentID' => $this->faker->word,
        'projectID' => $this->faker->randomDigitNotNull,
        'serialNo' => $this->faker->randomDigitNotNull,
        'companyFinanceYearID' => $this->faker->randomDigitNotNull,
        'FYBiggin' => $this->faker->date('Y-m-d H:i:s'),
        'FYEnd' => $this->faker->date('Y-m-d H:i:s'),
        'companyFinancePeriodID' => $this->faker->randomDigitNotNull,
        'FYPeriodDateFrom' => $this->faker->date('Y-m-d H:i:s'),
        'FYPeriodDateTo' => $this->faker->date('Y-m-d H:i:s'),
        'BPVcode' => $this->faker->word,
        'BPVdate' => $this->faker->date('Y-m-d H:i:s'),
        'BPVbank' => $this->faker->randomDigitNotNull,
        'BPVAccount' => $this->faker->randomDigitNotNull,
        'BPVchequeNo' => $this->faker->randomDigitNotNull,
        'BPVchequeDate' => $this->faker->date('Y-m-d H:i:s'),
        'BPVNarration' => $this->faker->word,
        'BPVbankCurrency' => $this->faker->randomDigitNotNull,
        'BPVbankCurrencyER' => $this->faker->randomDigitNotNull,
        'directPaymentpayeeYN' => $this->faker->randomDigitNotNull,
        'directPaymentPayeeSelectEmp' => $this->faker->randomDigitNotNull,
        'directPaymentPayeeEmpID' => $this->faker->word,
        'directPaymentPayee' => $this->faker->word,
        'directPayeeCurrency' => $this->faker->randomDigitNotNull,
        'directPayeeBankMemo' => $this->faker->text,
        'BPVsupplierID' => $this->faker->randomDigitNotNull,
        'supplierGLCodeSystemID' => $this->faker->randomDigitNotNull,
        'supplierGLCode' => $this->faker->word,
        'supplierTransCurrencyID' => $this->faker->randomDigitNotNull,
        'supplierTransCurrencyER' => $this->faker->randomDigitNotNull,
        'supplierDefCurrencyID' => $this->faker->randomDigitNotNull,
        'supplierDefCurrencyER' => $this->faker->randomDigitNotNull,
        'localCurrencyID' => $this->faker->randomDigitNotNull,
        'localCurrencyER' => $this->faker->randomDigitNotNull,
        'companyRptCurrencyID' => $this->faker->randomDigitNotNull,
        'companyRptCurrencyER' => $this->faker->randomDigitNotNull,
        'payAmountBank' => $this->faker->randomDigitNotNull,
        'payAmountSuppTrans' => $this->faker->randomDigitNotNull,
        'payAmountSuppDef' => $this->faker->randomDigitNotNull,
        'payAmountCompLocal' => $this->faker->randomDigitNotNull,
        'payAmountCompRpt' => $this->faker->randomDigitNotNull,
        'suppAmountDocTotal' => $this->faker->randomDigitNotNull,
        'createMonthlyDeduction' => $this->faker->word,
        'confirmedYN' => $this->faker->randomDigitNotNull,
        'confirmedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'confirmedByEmpID' => $this->faker->word,
        'confirmedByName' => $this->faker->word,
        'confirmedDate' => $this->faker->date('Y-m-d H:i:s'),
        'approved' => $this->faker->randomDigitNotNull,
        'approvedDate' => $this->faker->date('Y-m-d H:i:s'),
        'approvedByUserID' => $this->faker->word,
        'approvedByUserSystemID' => $this->faker->randomDigitNotNull,
        'postedDate' => $this->faker->date('Y-m-d H:i:s'),
        'invoiceType' => $this->faker->randomDigitNotNull,
        'matchInvoice' => $this->faker->randomDigitNotNull,
        'trsCollectedYN' => $this->faker->randomDigitNotNull,
        'trsCollectedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'trsCollectedByEmpID' => $this->faker->word,
        'trsCollectedByEmpName' => $this->faker->word,
        'trsCollectedDate' => $this->faker->date('Y-m-d H:i:s'),
        'trsClearedYN' => $this->faker->randomDigitNotNull,
        'trsClearedDate' => $this->faker->date('Y-m-d H:i:s'),
        'trsClearedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'trsClearedByEmpID' => $this->faker->word,
        'trsClearedByEmpName' => $this->faker->word,
        'trsClearedAmount' => $this->faker->randomDigitNotNull,
        'bankClearedYN' => $this->faker->randomDigitNotNull,
        'bankClearedAmount' => $this->faker->randomDigitNotNull,
        'bankReconciliationDate' => $this->faker->date('Y-m-d H:i:s'),
        'bankClearedDate' => $this->faker->date('Y-m-d H:i:s'),
        'bankClearedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'bankClearedByEmpID' => $this->faker->word,
        'bankClearedByEmpName' => $this->faker->word,
        'chequePaymentYN' => $this->faker->randomDigitNotNull,
        'chequePrintedYN' => $this->faker->randomDigitNotNull,
        'chequePrintedDateTime' => $this->faker->date('Y-m-d H:i:s'),
        'chequePrintedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'chequePrintedByEmpID' => $this->faker->word,
        'chequePrintedByEmpName' => $this->faker->word,
        'chequeSentToTreasury' => $this->faker->randomDigitNotNull,
        'chequeSentToTreasuryByEmpSystemID' => $this->faker->randomDigitNotNull,
        'chequeSentToTreasuryByEmpID' => $this->faker->word,
        'chequeSentToTreasuryByEmpName' => $this->faker->word,
        'chequeSentToTreasuryDate' => $this->faker->date('Y-m-d H:i:s'),
        'chequeReceivedByTreasury' => $this->faker->randomDigitNotNull,
        'chequeReceivedByTreasuryByEmpSystemID' => $this->faker->randomDigitNotNull,
        'chequeReceivedByTreasuryByEmpID' => $this->faker->word,
        'chequeReceivedByTreasuryByEmpName' => $this->faker->word,
        'chequeReceivedByTreasuryDate' => $this->faker->date('Y-m-d H:i:s'),
        'timesReferred' => $this->faker->randomDigitNotNull,
        'matchingConfirmedYN' => $this->faker->randomDigitNotNull,
        'matchingConfirmedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'matchingConfirmedByEmpID' => $this->faker->word,
        'matchingConfirmedByName' => $this->faker->word,
        'matchingConfirmedDate' => $this->faker->date('Y-m-d H:i:s'),
        'refferedBackYN' => $this->faker->randomDigitNotNull,
        'RollLevForApp_curr' => $this->faker->randomDigitNotNull,
        'noOfApprovalLevels' => $this->faker->randomDigitNotNull,
        'isRelatedPartyYN' => $this->faker->randomDigitNotNull,
        'advancePaymentTypeID' => $this->faker->randomDigitNotNull,
        'isPdcChequeYN' => $this->faker->randomDigitNotNull,
        'finalSettlementYN' => $this->faker->randomDigitNotNull,
        'partyTblID' => $this->faker->randomDigitNotNull,
        'expenseClaimOrPettyCash' => $this->faker->randomDigitNotNull,
        'interCompanyToSystemID' => $this->faker->randomDigitNotNull,
        'interCompanyToID' => $this->faker->word,
        'ReversedYN' => $this->faker->randomDigitNotNull,
        'cancelYN' => $this->faker->randomDigitNotNull,
        'cancelComment' => $this->faker->text,
        'cancelDate' => $this->faker->date('Y-m-d H:i:s'),
        'cancelledByEmpSystemID' => $this->faker->randomDigitNotNull,
        'canceledByEmpID' => $this->faker->word,
        'canceledByEmpName' => $this->faker->word,
        'createdUserGroup' => $this->faker->word,
        'createdUserSystemID' => $this->faker->randomDigitNotNull,
        'createdUserID' => $this->faker->word,
        'createdPcID' => $this->faker->word,
        'modifiedUserSystemID' => $this->faker->randomDigitNotNull,
        'modifiedUser' => $this->faker->word,
        'modifiedPc' => $this->faker->word,
        'createdDateTime' => $this->faker->date('Y-m-d H:i:s'),
        'timestamp' => $this->faker->date('Y-m-d H:i:s'),
        'rcmActivated' => $this->faker->randomDigitNotNull,
        'retentionVatAmount' => $this->faker->randomDigitNotNull,
        'VATAmount' => $this->faker->randomDigitNotNull,
        'VATAmountLocal' => $this->faker->randomDigitNotNull,
        'VATAmountRpt' => $this->faker->randomDigitNotNull,
        'netAmount' => $this->faker->randomDigitNotNull,
        'netAmountLocal' => $this->faker->randomDigitNotNull,
        'netAmountRpt' => $this->faker->randomDigitNotNull,
        'VATPercentage' => $this->faker->randomDigitNotNull,
        'pdcChequeYN' => $this->faker->randomDigitNotNull,
        'bankAccountBalance' => $this->faker->randomDigitNotNull,
        'payment_mode' => $this->faker->randomDigitNotNull,
        'advanceAccountSystemID' => $this->faker->randomDigitNotNull,
        'AdvanceAccount' => $this->faker->word,
        'VATAmountBank' => $this->faker->randomDigitNotNull,
        'applyVAT' => $this->faker->randomDigitNotNull
        ];
    }
}
