<?php

namespace Database\Factories;

use App\Models\PurchaseOrderMaster;
use Illuminate\Database\Eloquent\Factories\Factory;

class PurchaseOrderMasterFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = PurchaseOrderMaster::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'poProcessId' => $this->faker->randomDigitNotNull,
        'companySystemID' => $this->faker->randomDigitNotNull,
        'companyID' => $this->faker->word,
        'departmentID' => $this->faker->word,
        'orderType' => $this->faker->randomDigitNotNull,
        'amended' => $this->faker->randomDigitNotNull,
        'projectID' => $this->faker->randomDigitNotNull,
        'serviceLineSystemID' => $this->faker->randomDigitNotNull,
        'serviceLine' => $this->faker->word,
        'companyAddress' => $this->faker->text,
        'documentSystemID' => $this->faker->randomDigitNotNull,
        'documentID' => $this->faker->word,
        'purchaseOrderCode' => $this->faker->word,
        'serialNumber' => $this->faker->randomDigitNotNull,
        'supplierID' => $this->faker->randomDigitNotNull,
        'supplierPrimaryCode' => $this->faker->word,
        'supplierName' => $this->faker->text,
        'supplierAddress' => $this->faker->text,
        'supplierTelephone' => $this->faker->word,
        'supplierFax' => $this->faker->word,
        'supplierEmail' => $this->faker->word,
        'creditPeriod' => $this->faker->randomDigitNotNull,
        'expectedDeliveryDate' => $this->faker->date('Y-m-d H:i:s'),
        'narration' => $this->faker->text,
        'poLocation' => $this->faker->randomDigitNotNull,
        'financeCategory' => $this->faker->randomDigitNotNull,
        'referenceNumber' => $this->faker->word,
        'shippingAddressID' => $this->faker->randomDigitNotNull,
        'shippingAddressDescriprion' => $this->faker->text,
        'invoiceToAddressID' => $this->faker->randomDigitNotNull,
        'invoiceToAddressDescription' => $this->faker->text,
        'soldToAddressID' => $this->faker->randomDigitNotNull,
        'soldToAddressDescriprion' => $this->faker->text,
        'paymentTerms' => $this->faker->text,
        'deliveryTerms' => $this->faker->text,
        'panaltyTerms' => $this->faker->text,
        'localCurrencyID' => $this->faker->randomDigitNotNull,
        'localCurrencyER' => $this->faker->randomDigitNotNull,
        'companyReportingCurrencyID' => $this->faker->randomDigitNotNull,
        'companyReportingER' => $this->faker->randomDigitNotNull,
        'supplierDefaultCurrencyID' => $this->faker->randomDigitNotNull,
        'supplierDefaultER' => $this->faker->randomDigitNotNull,
        'supplierTransactionCurrencyID' => $this->faker->randomDigitNotNull,
        'supplierTransactionER' => $this->faker->randomDigitNotNull,
        'poConfirmedYN' => $this->faker->randomDigitNotNull,
        'poConfirmedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'poConfirmedByEmpID' => $this->faker->word,
        'poConfirmedByName' => $this->faker->word,
        'poConfirmedDate' => $this->faker->date('Y-m-d H:i:s'),
        'poCancelledYN' => $this->faker->randomDigitNotNull,
        'poCancelledBySystemID' => $this->faker->randomDigitNotNull,
        'poCancelledBy' => $this->faker->word,
        'poCancelledByName' => $this->faker->word,
        'poCancelledDate' => $this->faker->date('Y-m-d H:i:s'),
        'cancelledComments' => $this->faker->word,
        'poTotalComRptCurrency' => $this->faker->randomDigitNotNull,
        'poTotalLocalCurrency' => $this->faker->randomDigitNotNull,
        'poTotalSupplierDefaultCurrency' => $this->faker->randomDigitNotNull,
        'poTotalSupplierTransactionCurrency' => $this->faker->randomDigitNotNull,
        'poDiscountPercentage' => $this->faker->randomDigitNotNull,
        'poDiscountAmount' => $this->faker->randomDigitNotNull,
        'supplierVATEligible' => $this->faker->randomDigitNotNull,
        'VATPercentage' => $this->faker->randomDigitNotNull,
        'VATAmount' => $this->faker->randomDigitNotNull,
        'VATAmountLocal' => $this->faker->randomDigitNotNull,
        'VATAmountRpt' => $this->faker->randomDigitNotNull,
        'shipTocontactPersonID' => $this->faker->word,
        'shipTocontactPersonTelephone' => $this->faker->word,
        'shipTocontactPersonFaxNo' => $this->faker->word,
        'shipTocontactPersonEmail' => $this->faker->word,
        'invoiceTocontactPersonID' => $this->faker->word,
        'invoiceTocontactPersonTelephone' => $this->faker->word,
        'invoiceTocontactPersonFaxNo' => $this->faker->word,
        'invoiceTocontactPersonEmail' => $this->faker->word,
        'soldTocontactPersonID' => $this->faker->word,
        'soldTocontactPersonTelephone' => $this->faker->word,
        'soldTocontactPersonFaxNo' => $this->faker->word,
        'soldTocontactPersonEmail' => $this->faker->word,
        'priority' => $this->faker->randomDigitNotNull,
        'approved' => $this->faker->randomDigitNotNull,
        'approvedDate' => $this->faker->date('Y-m-d H:i:s'),
        'approvedByUserID' => $this->faker->word,
        'approvedByUserSystemID' => $this->faker->randomDigitNotNull,
        'approval_remarks' => $this->faker->word,
        'addOnPercent' => $this->faker->randomDigitNotNull,
        'addOnDefaultPercent' => $this->faker->randomDigitNotNull,
        'GRVTrackingID' => $this->faker->randomDigitNotNull,
        'logisticDoneYN' => $this->faker->randomDigitNotNull,
        'poClosedYN' => $this->faker->randomDigitNotNull,
        'grvRecieved' => $this->faker->randomDigitNotNull,
        'invoicedBooked' => $this->faker->randomDigitNotNull,
        'refferedBackYN' => $this->faker->randomDigitNotNull,
        'timesReferred' => $this->faker->randomDigitNotNull,
        'poType' => $this->faker->word,
        'poType_N' => $this->faker->randomDigitNotNull,
        'docRefNo' => $this->faker->word,
        'RollLevForApp_curr' => $this->faker->randomDigitNotNull,
        'sentToSupplier' => $this->faker->randomDigitNotNull,
        'sentToSupplierByEmpSystemID' => $this->faker->randomDigitNotNull,
        'sentToSupplierByEmpID' => $this->faker->word,
        'sentToSupplierByEmpName' => $this->faker->word,
        'sentToSupplierDate' => $this->faker->date('Y-m-d H:i:s'),
        'budgetBlockYN' => $this->faker->randomDigitNotNull,
        'budgetYear' => $this->faker->randomDigitNotNull,
        'hidePOYN' => $this->faker->randomDigitNotNull,
        'hideByEmpSystemID' => $this->faker->randomDigitNotNull,
        'hideByEmpID' => $this->faker->word,
        'hideByEmpName' => $this->faker->word,
        'hideDate' => $this->faker->date('Y-m-d H:i:s'),
        'hideComments' => $this->faker->text,
        'WO_purchaseOrderID' => $this->faker->randomDigitNotNull,
        'WO_PeriodFrom' => $this->faker->date('Y-m-d H:i:s'),
        'WO_PeriodTo' => $this->faker->date('Y-m-d H:i:s'),
        'WO_NoOfAutoGenerationTimes' => $this->faker->randomDigitNotNull,
        'WO_NoOfGeneratedTimes' => $this->faker->randomDigitNotNull,
        'WO_fullyGenerated' => $this->faker->randomDigitNotNull,
        'WO_amendYN' => $this->faker->randomDigitNotNull,
        'WO_amendRequestedDate' => $this->faker->date('Y-m-d H:i:s'),
        'WO_amendRequestedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'WO_amendRequestedByEmpID' => $this->faker->word,
        'WO_confirmedYN' => $this->faker->randomDigitNotNull,
        'WO_confirmedDate' => $this->faker->date('Y-m-d H:i:s'),
        'WO_confirmedByEmpID' => $this->faker->word,
        'WO_terminateYN' => $this->faker->randomDigitNotNull,
        'WO_terminatedDate' => $this->faker->date('Y-m-d H:i:s'),
        'WO_terminatedByEmpID' => $this->faker->word,
        'WO_terminateComments' => $this->faker->text,
        'partiallyGRVAllowed' => $this->faker->randomDigitNotNull,
        'logisticsAvailable' => $this->faker->randomDigitNotNull,
        'vatRegisteredYN' => $this->faker->randomDigitNotNull,
        'manuallyClosed' => $this->faker->randomDigitNotNull,
        'manuallyClosedByEmpSystemID' => $this->faker->randomDigitNotNull,
        'manuallyClosedByEmpID' => $this->faker->word,
        'manuallyClosedByEmpName' => $this->faker->word,
        'manuallyClosedDate' => $this->faker->date('Y-m-d H:i:s'),
        'manuallyClosedComment' => $this->faker->text,
        'supCategoryICVMasterID' => $this->faker->randomDigitNotNull,
        'supCategorySubICVID' => $this->faker->randomDigitNotNull,
        'createdUserGroup' => $this->faker->word,
        'createdPcID' => $this->faker->word,
        'createdUserSystemID' => $this->faker->randomDigitNotNull,
        'createdUserID' => $this->faker->word,
        'modifiedPc' => $this->faker->word,
        'modifiedUserSystemID' => $this->faker->randomDigitNotNull,
        'modifiedUser' => $this->faker->word,
        'createdDateTime' => $this->faker->date('Y-m-d H:i:s'),
        'isSelected' => $this->faker->word,
        'timeStamp' => $this->faker->date('Y-m-d H:i:s'),
        'allocateItemToSegment' => $this->faker->randomDigitNotNull,
        'workOrderGenerateID' => $this->faker->randomDigitNotNull,
        'rcmActivated' => $this->faker->randomDigitNotNull,
        'poTypeID' => $this->faker->randomDigitNotNull,
        'categoryID' => $this->faker->randomDigitNotNull,
        'upload_job_status' => $this->faker->randomDigitNotNull,
        'isBulkItemJobRun' => $this->faker->randomDigitNotNull,
        'vat_number' => $this->faker->word
        ];
    }
}
